# Generated by Django 5.0.6 on 2025-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('prefeitura', models.CharField(max_length=150, verbose_name='Prefeitura')),
                ('departamento', models.CharField(blank=True, max_length=150, verbose_name='Departamento')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='orgaos/%Y/%m/', verbose_name='Logo')),
                ('assinatura_fiscal', models.ImageField(blank=True, null=True, upload_to='orgaos/assinaturas/%Y/%m/', verbose_name='Assinatura Fiscal')),
                ('assinatura_engenheiro', models.ImageField(blank=True, null=True, upload_to='orgaos/assinaturas/%Y/%m/', verbose_name='Assinatura Engenheiro')),
                ('assinatura_gestor', models.ImageField(blank=True, null=True, upload_to='orgaos/assinaturas/%Y/%m/', verbose_name='Assinatura Gestor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
                'ordering': ['prefeitura', 'departamento', 'nome'],
            },
        ),
    ]
