# Generated by Django 5.0.6 on 2025-08-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_local_latitude_local_longitude_alter_local_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='link_maps',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Google Maps'),
        ),
    ]
