# Generated by Django 5.0.6 on 2025-07-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('data_paralisado', models.DateField(blank=True, null=True)),
                ('motivo_pendente_paralisado', models.TextField(blank=True)),
                ('situacao', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('pendente', 'Pendente'), ('paralisado', 'Paralisado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('situacao', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('pendente', 'Pendente'), ('paralisado', 'Paralisado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], max_length=20)),
                ('quantidade', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordemservico.categoria')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='ordemservico.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='FotoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_servico/')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordemservico.servico')),
            ],
        ),
    ]
