# Generated by Django 5.0.6 on 2025-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('local', '0001_initial'),
        ('ordemservico', '0002_ordemservico_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.UniqueConstraint(fields=('contrato', 'numero'), name='unique_numero_por_contrato'),
        ),
    ]
