# Generated by Django 5.0.6 on 2025-07-29 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('ordemservico', '0003_alter_ordemservico_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='contratos.contrato'),
        ),
    ]
