# Generated by Django 5.0.6 on 2025-07-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservico', '0004_alter_ordemservico_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='quantidade',
            field=models.TextField(blank=True, null=True),
        ),
    ]
