# Generated by Django 5.0.6 on 2025-08-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservico', '0006_album_foto_delete_fotoservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='urgente',
            field=models.BooleanField(default=False, verbose_name='Urgente'),
        ),
    ]
