# Generated by Django 5.0.6 on 2025-08-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservico', '0007_ordemservico_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='urgente',
            field=models.BooleanField(default=False, verbose_name='Urgente'),
        ),
    ]
