# Generated by Django 5.0.6 on 2025-08-21 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservico', '0008_servico_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_solicitacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Solicitação'),
        ),
        migrations.AddField(
            model_name='servico',
            name='data_finalizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Finalização'),
        ),
        migrations.AddField(
            model_name='servico',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de Entrega'),
        ),
    ]
