# Generated by Django 5.0.6 on 2025-07-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Nº do Contrato')),
                ('objeto', models.TextField(verbose_name='Objeto do Contrato')),
                ('empresa_contratada', models.CharField(max_length=200, verbose_name='Empresa Contratada')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('orgao_contratante', models.CharField(max_length=200, verbose_name='Órgão Público Contratante')),
                ('fiscal', models.CharField(max_length=100, verbose_name='Fiscal do Contrato')),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('encerrado', 'Encerrado'), ('rescindido', 'Rescindido'), ('suspenso', 'Suspenso')], default='vigente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
